# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\1dustindavis\gorilla

environment:
  GOPATH: c:\gopath

stack: go 1.11

install:
  - cinst make
  - cinst grep

before_test:
  - make lint

test_script:
  - make test