version: gorilla-appveyor-{build}
branches:
  only:
  - master
clone_folder: c:\gopath\src\github.com\1dustindavis\gorilla
environment:
  GOPATH: c:\gopath
install:
- ps: >-
    # Define build variables

    $APP_NAME = "gorilla"

    $VERSION = git describe --tags --always --dirty

    $BRANCH = $env:APPVEYOR_REPO_BRANCH

    $NOW = Get-Date -format s

    $REVISION = git rev-parse HEAD

    $GOVERSION = (go version).Split()[2]


    Set-AppveyorBuildVariable -Name "gorilla_app_name" -Value $APP_NAME

    Set-AppveyorBuildVariable -Name "gorilla_version" -Value $VERSION

    Set-AppveyorBuildVariable -Name "gorilla_branch" -Value $BRANCH

    Set-AppveyorBuildVariable -Name "gorilla_now" -Value $NOW

    Set-AppveyorBuildVariable -Name "gorilla_revision" -Value $REVISION

    Set-AppveyorBuildVariable -Name "gorilla_goversion" -Value $GOVERSION


    # Setup dependencies

    $env:Path += ";c:\gopath\bin"

    go get -u github.com/golang/dep/...

    go get -u github.com/golang/lint/golint

    dep ensure
build_script:
- ps: >-
    $BUILD_VERSION = "-X github.com/1dustindavis/gorilla/pkg/version.appName=$env:gorilla_app_name " +
                    "-X github.com/1dustindavis/gorilla/pkg/version.version=$env:gorilla_version " +
                    "-X github.com/1dustindavis/gorilla/pkg/version.branch=$env:gorilla_branch " +
                    "-X github.com/1dustindavis/gorilla/pkg/version.buildDate=$env:gorilla_now " +
                    "-X github.com/1dustindavis/gorilla/pkg/version.revision=$env:gorilla_revision " +
                    "-X github.com/1dustindavis/gorilla/pkg/version.goVersion=$env:gorilla_goversion"

    # Make our build directory and run the build command

    mkdir build > $null

    go build -i -o build/gorilla.exe -ldflags $BUILD_VERSION ./cmd/gorilla
test_script:
- ps: >-
    # Add the go bin directory to the path

    $env:Path += ";c:\gopath\bin;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin"


    # Error if gofmt returns anything

    If (gofmt -l ./cmd/ ./pkg/) {
        Write-Error "Repo contains improperly formatted go files; run gofmt -w *.go"
    }


    # Run go vet and go lint

    go vet ./...

    golint ./cmd/ ./pkg/


    # Run tests

    go test -cover -race ./...
artifacts:
- path: build/gorilla.exe
  name: gorilla_build
deploy: off