# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\1dustindavis\gorilla

environment:
  GOPATH: c:\gopath

stack: go 1.11

before_test:
  # Resolve all of our dependencies
  - go get -u github.com/golang/dep/...
  - go get -u github.com/golang/lint/golint
  - dep ensure -vendor-only -v
  # Run linters
  - ps: |
    If (gofmt -l ./cmd/ ./pkg/) {
      Write-Error "Repo contains improperly formatted go files; run gofmt -w *.go"
    }
  - go vet ./...
  - golint ./cmd/ ./pkg/

test_script:
  - gotest -cover -race ./...